### ISSUE TITLE
match multiple arguments

### ISSUE THREAD

**Issue by rogpeppe** [mvdan/gogrep#7] opened 2017-09-18 11:35 UTC
It might be useful to be able to match a variable number of arguments
passed to a function.

For example:

     gogrep 'if err != nil { return fmt.Errorf($_*, err)

This applies more when replacing the pattern with something else:

    funcWithVariableArgs($a, $rest*) -> otherFunc($rest)

**Comment by mvdan** [comment] 2017-09-18 11:38
I would say this is a duplicate of #2. Arguments are just expressions, and we already support matching expression lists - so `$*` will fit into that nicely.

**Comment by rogpeppe** [comment] 2017-09-18 11:48
I thought it justified a separate issue, because #2 only mentions statements, not expressions too, and the implementation will likely be significantly different as a result. Perhaps mention multiple expressions too in #2 and close this?

**Comment by mvdan** [comment] 2017-09-18 11:49
Well, #2 mentions nodes - it's perhaps confusing because I only used statements as an example. I'll add an expressions example too.

**Closed by mvdan** 2017-09-18 11:49 UTC
